# Generated by Django 5.1.5 on 2025-05-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('Total_Clauses', models.IntegerField()),
                ('Dangerous_Clauses', models.IntegerField()),
                ('suggestions_generated', models.TextField()),
                ('suggestions', models.IntegerField()),
                ('Proofreading_score', models.IntegerField()),
            ],
        ),
    ]
