# Generated by Django 5.1.5 on 2025-05-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clause_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_text',
            name='Text',
            field=models.CharField(max_length=1000000),
        ),
    ]
